### ISSUE TITLE
First steps in the work in progess

### ISSUE THREAD

**Issue by astridx** [joomla-projects/virtualisation#1]
I created today the default enviroment with

```
$generator = new DockerComposeGenerator('tests/fixtures');
$generator->write('dockyard/docker-compose.yml');
```

The directory dockyard was created successfully. But the command 

`docker-compose up`

end with failures while building a dockerfile.

I first got the error

 `Unknown instruction: &&.`

I figured out, that an empty line was the problem.(https://github.com/moby/moby/issues/28587)

After I deleted the empty line 142 in the file /dockyard/docker/php-5.2/Dockerfile I got another error message:

`Missing ':' in substitution: ${gpg.keys}`

The problem is the line

`ENV GPG_KEYS ${gpg.keys}
`
I do not understand this message exactly, but perhaps here is the solution for this:
http://stackoverflow.com/questions/37940988/how-to-change-docker-env-var
![emtyline](https://cloud.githubusercontent.com/assets/9974686/25766055/713962c4-31f0-11e7-9f01-74115772311f.png)

**Comment by astridx** [comment]
@nibra 
Thank you for the quick reply. I applied your PR and I had another test now.

For version apache5.2 there is no GPG Key in the Dockerfile.
I only see the entry without a value. And thats why I can not build the docker image.

`ENV GPG_KEYS `

I had a look. We count this key within the vendor - file: 

`vendor/greencape/php-versions/src/PhpVersions.php
`

For version apache5.6 I see a GPS Key.

`ENV GPG_KEYS 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3 0BD78B5F97500D450838F95DFE857D9A90D90EC1
`



The next error is: I can not build the image because the of the new line after clean - you see it for in the picture. This line is in all apache Dockerfiles. With this line I see this error message:

```
virtualisation/dockyard/docker/apache-5.6$ docker build .
Sending build context to Docker daemon 22.64 MB
Error response from daemon: Unknown instruction: &&

```

When I delete the line the creation of the images starts, when I enter 
`docker build .
`
But I get error messages:
Here I attach the files for apache5.6



[log.log.zip](https://github.com/joomla-projects/virtualisation/files/980781/log.log.zip)
[apache-5.6.zip](https://github.com/joomla-projects/virtualisation/files/980782/apache-5.6.zip)

**Comment by nibra** [comment]
Missing GPG keys are no problem, the script works with an empty list of keys.
The newline (it is a missing backslash) is fixed in the PR. I'm still working on it, as there are some compile problems left.

The PHP version information is cached on your local system for a week or so. To get the latest information (updated the php-versions repo last night), purge the cache:

    $ rm ~/.php_versions

Opend a new issue #3 for the error from your log file.

**Comment by astridx** [comment]
@nibra 
Missing GPG keys are a problem, because the build breaks with the error message

```
docker build .
Sending build context to Docker daemon 22.67 MB
Error response from daemon: ENV must have two arguments
```

So we should not integrate the 

`ENV GPG_KEYS
`
into the Dockerfile, if there is no key.

Should I have to look for this issue and create an PR? 


- - - 


> The newline (it is a missing backslash) is fixed in the PR. I'm still working on it, as there are some compile problems left.

I applied your PR, but I sill see the new line. 

Sorry that I can't contribute more. I have to start with smaller Dockerfiles and docker-compose.yml files :(

**Comment by nibra** [comment]
> ENV must have two arguments

Have that corrected already (not yet in the PR, but it is coming) - there were 2 places :(.

**Comment by nibra** [comment]
All images build now.
